"""'photo'

Revision ID: 563f4fd3116b
Revises: 1e94a6372ffe
Create Date: 2018-03-28 10:18:19.254340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563f4fd3116b'
down_revision = '1e94a6372ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###
